import type { Config } from 'tailwindcss'
import animate from 'tailwindcss-animate'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Academic Kinetic color system
        primary: '#9cff93',
        'primary-fixed': '#00fc40',
        'primary-fixed-dim': '#00ec3b',
        'primary-dim': '#00ec3b',
        'primary-container': '#00fc40',
        'on-primary': '#006413',
        'on-primary-fixed': '#00440a',
        'on-primary-fixed-variant': '#006513',
        'on-primary-container': '#005a10',
        secondary: '#89faaa',
        'secondary-fixed': '#89faaa',
        'secondary-fixed-dim': '#7aeb9d',
        'secondary-dim': '#7aeb9d',
        'secondary-container': '#006d38',
        'on-secondary': '#005f30',
        'on-secondary-fixed': '#004a24',
        'on-secondary-fixed-variant': '#006a36',
        'on-secondary-container': '#e3ffe5',
        tertiary: '#8af2ff',
        'tertiary-fixed': '#0eeafd',
        'tertiary-fixed-dim': '#00dbec',
        'tertiary-dim': '#00dbec',
        'tertiary-container': '#0eeafd',
        'on-tertiary': '#005b63',
        'on-tertiary-fixed': '#003d42',
        'on-tertiary-fixed-variant': '#005c64',
        'on-tertiary-container': '#005159',
        error: '#ff7351',
        'error-dim': '#d53d18',
        'error-container': '#b92902',
        'on-error': '#450900',
        'on-error-container': '#ffd2c8',
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-variant': '#262626',
        'surface-tint': '#9cff93',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#1a1919',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        background: '#0e0e0e',
        'on-background': '#ffffff',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        outline: '#777575',
        'outline-variant': '#494847',
        'inverse-surface': '#fcf8f8',
        'inverse-on-surface': '#565554',
        'inverse-primary': '#006f16',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      letterSpacing: {
        'ultra-wide': '1.5rem',
      },
    },
  },
  plugins: [animate],
}

export default config
