services:
  postgres:
    image: postgres:16-alpine
    container_name: utaxi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: utaxi
      POSTGRES_USER: utaxi
      POSTGRES_PASSWORD: utaxi123
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utaxi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
